version: '3'

services:
        jenkins:
                image: jenkins/jenkins:lts
                container_name: jenkins
                restart: always
                user: root
                ports:
                        - "8090:8080"
                        - "50000:50000"
                volumes:
                        - "/home/ubuntu/hrtest/s03p13b105/jenkins/jenkins_home:/var/jenkins_home"
        
        nginx:
                image: nginx:latest
                container_name: nginx
                ports:
                        - "8001:80"
                volumes:
                        - "/home/ubuntu/hrtest/s03p13b105/nginx/conf.d:/etc/nginx/conf.d"

